--- #YAML:1.0
name: DateTime-TimeZone-Alias
version: 0.0501
author: ~
abstract: ~
license: perl
requires:
  DateTime: 0
  DateTime::TimeZone: 0.25
provides:
  DateTime::TimeZone::Alias:
    file: lib/DateTime/TimeZone/Alias.pm
    version: 0.0501
generated_by: Module::Build version 0.25
